name: Generate Js13k submission zip

on:
  push:

  workflow_dispatch:

env:
  INPUT_JS: Grave.js
  MINIFIED_JS: Mini.js
  SHRUNK_JS: Micro.js
  INPUT_HTML: micro.html
  OUTPUT_HTML: index.html
  ADDITIONAL_OUTPUT_FILES:
  OUTPUT_ZIP: Grave.zip
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install node/npx
        uses: actions/setup-node@v3

      - name: Minify with terser
        run: npx terser --compress --output $MINIFIED_JS -- $INPUT_JS

      - name: Shrink with roadroller
        run: npx roadroller $MINIFIED_JS --optimize 2 -o $SHRUNK_JS
        
      # JS13k rules need landing html to be index.html
      - name: Rename html to index.html
        run: mv $INPUT_HTML $OUTPUT_HTML

        
      - name: Zip
        run: |
          zip -9 ./$OUTPUT_ZIP $SHRUNK_JS $OUTPUT_HTML $ADDITIONAL_OUTPUT_FILES
          ls -l ./$OUTPUT_ZIP

      # mac: stat -f %z
      # linux: stat -c %s
      - name: Get final zip size
        run: |
          FILE_SIZE=`stat -c %s ./$OUTPUT_ZIP`
          echo "Final zip size $FILE_SIZE"
          echo "ZIP_SIZE=$FILE_SIZE" >> $GITHUB_ENV

      - name: Fail if final zip size invalid
        if: ${{ env.ZIP_SIZE == 0 }}
        run: exit 1

      - name: Fail if final zip size too big
        if: ${{ env.ZIP_SIZE > 13312 }}
        run: exit 1
      
      - name: Upload Final zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: GraveQuest
          path: ${{ env.OUTPUT_ZIP }}
